### ISSUE TITLE
how to increase the threads used in prune_graph.pl

### ISSUE THREAD

**Issue by xilingsabatelli** [fgvieira/ngsLD#22]
Hello!

I am running prune_graph.pl for my data (contains around 3 million SNPs), it takes endless time (already 19 days). I allocate 64 threads for the program by adding --n_threads, but I think this option doesn't applicable for prune_graph.pl. And I checked, the program is actually using only one thread. 

So is it possible to increase the threads for prune_graph.pl to somehow make it runs faster?

Many thanks,
Xiling

**Comment by fgvieira** [comment]
Hi Xiling,

the `prune_graph.pl` is not threaded, so it can be very slow.

The reason is that, it was initially made as a proof-of concept rather then for production. That is why it was made in `perl` and not a lot of attention was paid to optimization and such. One thing you can do, is to split the `ngsLD` output by contig/scaffold/chr and run the script on each one of them separately.
